### ISSUE TITLE
Recursive load

### ISSUE THREAD

**Issue by seanfarley** [purcell/whole-line-or-region#10]
Seems something recently changed and I'm now getting this:

```
Recursive load: "/Users/sean/projects/doom-emacs/.local/straight/build/whole-line-or-region/whole-line-or-region.elc", "/Users/sean/projects/doom-emacs/.local/straight/build/whole-line-or-region/whole-line-or-region.elc", "/Users/sean/projects/doom-emacs/.local/straight/build/whole-line-or-region/whole-line-or-region.elc", "/Users/sean/projects/doom-emacs/.local/straight/build/whole-line-or-region/whole-line-or-region.elc", "/Users/sean/projects/doom-emacs/.local/straight/build/whole-line-or-region/whole-line-or-region.elc"
```

**Comment by purcell** [comment]
Yeah, saw that - I'm looking into it. Sorry for the inconvenience.

**Comment by purcell** [comment]
Fixed now. It was caused by a straightforward fix for a byte compilation warning, but that obviously uncovered a strange behaviour, so I'll find a better approach. I adopted this package a while ago, and haven't really got deeply into its quirks.

**Comment by seanfarley** [comment]
No worries! Thanks for all your hard work! Totes understand about quirks :-)
