### ISSUE TITLE
How to configure `whole-line-or-region` to use `cua-mode` copy/paste shortcuts

### ISSUE THREAD

**Issue by sridharrajs** [purcell/whole-line-or-region#11]
First of all, thanks for `whole-line-or-region`. I trying to set `whole-line-or-region` to use `cua-mode` shortcuts. Can you please point me to how I can configure it. Thanks

**Comment by purcell** [comment]
I've never done this, and I'm not quite sure what you mean.

As far as I know, `cua-mode` binds certain keys to `cua-*` commands, e.g. `cua-cut-region` and `cua-paste`, and those aren't particularly overridden by `whole-line-or-region`, so there wouldn't be anything "in" `whole-line-or-region` to bind those keys to.

**Comment by purcell** [comment]
Closing due to lack of information, but if you tell me more I'm happy to comment.
