### ISSUE TITLE
whole-line-or-region-comment-dwim does not work anymore

### ISSUE THREAD

**Issue by thomasf** [purcell/whole-line-or-region#2]
It looks like adding comments is failing leaving an visible region between
beginning of line and point after being executed while removing comments always
works.

The kill and yank bindings seems to be working properly and I don't
remember having any issues with them since the upgrade.

     
I've tried running the function using `M-x` and my C-c ; binding from the configuration below:

```el
(use-package whole-line-or-region
  :ensure t
  :commands (whole-line-org-region-mode)
  :bind (
         ("C-c ;" . whole-line-or-region-comment-dwim)
         ("C-w" . whole-line-or-region-kill-region)
         ("C-y" . whole-line-or-region-yank))
  :init
  (progn
    (define-key region-bindings-mode-map ";" 'whole-line-or-region-comment-dwim)
    ))
```

I ran out of time trying to understand the significant difference between the
old and new code so I just replaced the source code in my elpa/ directory with
a60e022 to get my environment working again, for now.

**Comment by purcell** [comment]
Thanks for filing this separately, @thomasf. I'll take a look this weekend if time allows.

**Comment by purcell** [comment]
Fixed now thanks to @will08rien
