### ISSUE TITLE
rest-of-the-line-or-region 

### ISSUE THREAD

**Issue by drzraf** [purcell/whole-line-or-region#20]
Killing the rest of the line (if nothing is selected) or the region otherwise is the behavior I would like to have (using C-k).
Do you think I should consider trying to use this package for such a purpose or do you know of a better way?

**Comment by purcell** [comment]
It sounds like in neither of those cases would you want the command to act on the whole line, so I'd say you should just roll that command yourself. Something like this (completely untested):

```
(defun my-kill-line ()
   (interactive)
   (if (use-region-p)
       (kill-region (region-beginning) (region-end))
     (kill-line)))
 ```
