### ISSUE TITLE
Appending wrong to kill-ring

### ISSUE THREAD

**Issue by moyamo** [purcell/whole-line-or-region#3]
In version 1.3.1 if you had a buffer (where `|` is the cursor).

```
|Line 1
Line 2
```

Then typing `C-w C-w C-y` (kill two lines, then paste killed lines) would leave the buffer unchanged (as it should).

However in the master branch this currently results in

```
Line 2Line1
```

It doesn't append the newlines and it appends in the wrong order.

From what I can tell this bug was introduced in this range of commits a60e022...d840fbc

**Comment by purcell** [comment]
Sorry it took so long to get to this: the bug is now fixed. :-)
