### ISSUE TITLE
This doens't seem to work to download from melpa

### ISSUE THREAD

**Issue by JSpenced** [purcell/whole-line-or-region#6]
Can you update the link for the package?

**Comment by JSpenced** [comment]
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations [2 times]
Contacting host: melpa.org:443
package-install-from-archive: https://melpa.org/packages/whole-line-or-region-20180325.419.el: Not found

**Comment by purcell** [comment]
You need to refresh your package list. MELPA has built a new package version, but your local package list doesn't know about it -- we don't keep old versions on the MELPA server.
