### ISSUE TITLE
it seems M-w would make buffer state modified when whole-line-or-region-mode is on

### ISSUE THREAD

**Issue by chengyi** [purcell/whole-line-or-region#8]
As descripted in the title.

Thanks.

**Comment by purcell** [comment]
I cannot reproduce this, sorry. Please can you verify this using `emacs -Q` and then manually loading `whole-line-or-region-mode.el`?

**Comment by chengyi** [comment]
@purcell sorry for late response, it works well in clean emacs. it seems other code make the package wrong. so I will close this issue. Thanks.
